# Generated by Django 5.0.1 on 2024-01-25 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_description', models.TextField()),
                ('video_file', models.FileField(upload_to='upload_files/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'ts', 'mov'])])),
                ('video_thumbnail', models.ImageField(upload_to='upload_files/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png'])])),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
