# Generated by Django 5.0.1 on 2024-01-29 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoitem',
            name='video_file',
        ),
        migrations.AddField(
            model_name='videoitem',
            name='video_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=2083),
            preserve_default=False,
        ),
    ]
