# Generated by Django 5.0.1 on 2024-03-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
