# Generated by Django 5.0.1 on 2024-03-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='video_price',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
    ]
